#pragma once

namespace SoundId {
enum Enum {
	No_sound = 0,
	Zerg_Drone_ZDrErr00_WAV = 1,
	Misc_Buzz_wav_1 = 2,
	Misc_PError_WAV = 3,
	Misc_ZBldgPlc_wav_1 = 4,
	Misc_TBldgPlc_wav = 5,
	Misc_PBldgPlc_wav = 6,
	Misc_ExploLrg_wav = 7,
	Misc_ExploMed_wav = 8,
	Misc_ExploSm_wav = 9,
	Misc_Explo1_wav = 10,
	Misc_Explo2_wav = 11,
	Misc_Explo3_wav = 12,
	Misc_Explo4_wav = 13,
	Misc_Explo5_wav = 14,
	Misc_Button_wav = 15,
	Misc_BurrowDn_wav = 16,
	Misc_BurrowUp_wav = 17,
	Misc_OnFirSml_wav = 18,
	Misc_IntoNydus_wav = 19,
	Misc_OutOfGas_wav = 20,
	Misc_youwin_wav = 21,
	Misc_youlose_wav = 22,
	Misc_Transmission_wav = 23,
	Misc_Door_Door1Opn_wav = 24,
	Misc_Door_Door1Cls_wav = 25,
	Misc_Door_Door2Opn_wav = 26,
	Misc_Door_Door2Cls_wav = 27,
	Misc_Door_Door3Opn_wav = 28,
	Misc_Door_Door3Cls_wav = 29,
	Misc_Door_Door4Opn_wav = 30,
	Misc_Door_Door4Cls_wav = 31,
	Misc_ZRescue_wav = 32,
	Misc_TRescue_wav = 33,
	Misc_PRescue_wav = 34,
	terran_SCV_EDrRep00_wav = 35,
	terran_SCV_EDrRep01_wav = 36,
	terran_SCV_EDrRep02_wav = 37,
	terran_SCV_EDrRep03_wav = 38,
	terran_SCV_EDrRep04_wav = 39,
	Misc_ZOvTra00_wav = 40,
	Misc_TDrTra00_wav = 41,
	Misc_PShTra00_wav = 42,
	Misc_ZOvTra01_wav = 43,
	Misc_TDrTra01_wav = 44,
	Misc_PShTra01_wav = 45,
	Misc_CRITTERS_JCrWht00_wav = 46,
	Misc_CRITTERS_JCrWht01_wav = 47,
	Misc_CRITTERS_JCrWht02_wav = 48,
	Misc_CRITTERS_JCrDth00_wav = 49,
	Misc_CRITTERS_LCrWht00_wav = 50,
	Misc_CRITTERS_LCrWht01_wav = 51,
	Misc_CRITTERS_LCrWht02_wav = 52,
	Misc_CRITTERS_LCrDth00_wav = 53,
	Misc_CRITTERS_BCrWht00_wav = 54,
	Misc_CRITTERS_BCrWht01_wav = 55,
	Misc_CRITTERS_BCrWht02_wav = 56,
	Misc_CRITTERS_BCrDth00_wav = 57,
	Bullet_PArFir00_wav = 58,
	Bullet_ZHyFir00_wav = 59,
	Bullet_ZHyHit00_wav = 60,
	Bullet_ZDrHit00_wav = 61,
	Bullet_LaserHit_wav = 62,
	Bullet_pshield_wav = 63,
	Bullet_SpoogHit_wav = 64,
	Bullet_BlastCan_wav = 65,
	Bullet_BlastGn2_wav = 66,
	Bullet_ZBGHit00_wav = 67,
	Bullet_TTaFir00_wav = 68,
	Bullet_TMaFir00_wav = 69,
	Bullet_TGoFir00_wav = 70,
	Bullet_ZGuFir00_wav = 71,
	Bullet_ZGuHit00_wav = 72,
	Bullet_LASERB_wav = 73,
	Bullet_TPhFi100_wav = 74,
	Bullet_LASRHIT1_wav = 75,
	Bullet_LASRHIT2_wav = 76,
	Bullet_LASRHIT3_wav = 77,
	Bullet_ZLuFir00_wav = 78,
	Bullet_ZLuHit00_wav = 79,
	Bullet_HKMISSLE_wav = 80,
	Bullet_TGoFi200_wav = 81,
	Bullet_TPhFi200_wav = 82,
	Bullet_TNsFir00_wav_1 = 83,
	Bullet_TNsFir00_wav_2 = 84,
	Bullet_TNsHit00_wav = 85,
	Bullet_PhoAtt00_wav = 86,
	Bullet_PhoHit00_wav = 87,
	Bullet_PSIBLADE_wav = 88,
	Bullet_PSIBOLT_wav = 89,
	Bullet_ZQuFir00_wav = 90,
	Bullet_ZQuHit00_wav = 91,
	Bullet_ZQuHit01_wav = 92,
	Bullet_ZQuHit02_wav = 93,
	Bullet_tscFir00_wav = 94,
	Bullet_SHOCKBMB_wav = 95,
	Bullet_TTaFi200_wav = 96,
	Bullet_SHCKLNCH_wav = 97,
	Bullet_TGhFir00_wav = 98,
	Bullet_DragBull_wav = 99,
	Bullet_psaHit00_wav = 100,
	Bullet_LaserB_wav = 101,
	Bullet_pTrFir00_wav = 102,
	Bullet_pTrFir01_wav = 103,
	Bullet_pzeFir00_wav = 104,
	Bullet_tbaFir00_wav = 105,
	Bullet_tvuFir00_wav = 106,
	Bullet_tvuHit00_wav = 107,
	Bullet_tvuHit01_wav = 108,
	Bullet_tvuHit02_wav = 109,
	Bullet_zdeAtt00_wav = 110,
	Bullet_UZeFir00_wav = 111,
	Bullet_UKiFir00_wav = 112,
	Bullet_zmuFir00_wav = 113,
	Misc_ZPwrDown_wav = 114,
	Misc_TPwrDown_wav = 115,
	Misc_PPwrDown_wav = 116,
	Zerg_Advisor_ZAdUpd00_WAV = 117,
	Terran_Advisor_TAdUpd00_WAV = 118,
	Protoss_Advisor_PAdUpd00_WAV = 119,
	Zerg_Advisor_ZAdUpd01_WAV = 120,
	Terran_Advisor_TAdUpd01_WAV = 121,
	Protoss_Advisor_PAdUpd01_WAV = 122,
	Zerg_Advisor_ZAdUpd02_WAV = 123,
	Terran_Advisor_TAdUpd02_WAV_1 = 124,
	Protoss_Advisor_PAdUpd02_WAV = 125,
	Terran_Advisor_TAdUpd03_WAV = 126,
	Zerg_Advisor_ZAdUpd04_WAV = 127,
	Terran_Advisor_TAdUpd04_WAV = 128,
	Protoss_Advisor_PAdUpd04_WAV = 129,
	Terran_Advisor_TAdUpd05_WAV = 130,
	Terran_Advisor_TAdUpd06_WAV = 131,
	Terran_Advisor_TAdUpd02_WAV_2 = 132,
	Protoss_Advisor_PAdUpd06_WAV = 133,
	Terran_Advisor_TAdUpd07_WAV = 134,
	Zerg_Bldg_ZChRdy00_WAV = 135,
	Terran_SCV_TSCUpd00_WAV = 136,
	Zerg_DRONE_ZDrErr00_WAV_1 = 137,
	Zerg_DRONE_ZDrErr00_WAV_2 = 138,
	Misc_Buzz_wav_2 = 139,
	Misc_PError_wav = 140,
	Misc_ZBldgPlc_wav_2 = 141,
	Terran_Advisor_tAdErr04_WAV_1 = 142,
	Terran_Advisor_tAdErr03_WAV_1 = 143,
	Terran_Advisor_tAdErr03_WAV_2 = 144,
	Terran_Advisor_tAdErr04_WAV_2 = 145,
	Zerg_Advisor_ZAdErr00_WAV_1 = 146,
	Zerg_Advisor_ZAdErr00_WAV_2 = 147,
	Terran_Advisor_tAdErr00_WAV = 148,
	Protoss_Advisor_PAdErr00_WAV = 149,
	Zerg_Advisor_ZAdErr01_WAV = 150,
	Terran_Advisor_tAdErr01_WAV = 151,
	Protoss_Advisor_PAdErr01_WAV = 152,
	Zerg_Advisor_ZAdErr02_WAV = 153,
	Terran_Advisor_tAdErr02_WAV = 154,
	Protoss_Advisor_PAdErr02_WAV = 155,
	Zerg_Advisor_ZAdErr06_WAV = 156,
	Terran_Advisor_tAdErr06_WAV = 157,
	Protoss_Advisor_PAdErr06_WAV = 158,
	Terran_SCV_TSCErr01_WAV = 159,
	Terran_Advisor_tAdErr04_WAV_3 = 160,
	Protoss_PROBE_PPrErr00_WAV = 161,
	Terran_SCV_TSCErr00_WAV = 162,
	Terran_Advisor_tAdErr04_WAV_4 = 163,
	Protoss_PROBE_PPrErr01_WAV = 164,
	glue_mousedown2_wav = 165,
	glue_mouseover_wav = 166,
	glue_bnetclick_wav = 167,
	glue_scorefill_wav = 168,
	glue_scorefillend_wav = 169,
	glue_countdown_wav = 170,
	glue_swishlock_wav = 171,
	glue_swishin_wav = 172,
	glue_swishout_wav = 173,
	Terran_SCV_TSCMin00_wav = 174,
	Terran_SCV_TSCMin01_wav = 175,
	Terran_BATTLE_tbardy00_wav = 176,
	Terran_BATTLE_tbaDth00_wav = 177,
	Terran_BATTLE_tBaYam01_wav = 178,
	Terran_BATTLE_tBaYam02_wav = 179,
	Terran_BATTLE_tbapss00_wav = 180,
	Terran_BATTLE_tbapss01_wav = 181,
	Terran_BATTLE_tbapss02_wav = 182,
	Terran_BATTLE_tbapss03_wav = 183,
	Terran_BATTLE_tbapss04_wav = 184,
	Terran_BATTLE_tbawht00_wav = 185,
	Terran_BATTLE_tbawht01_wav = 186,
	Terran_BATTLE_tbawht02_wav = 187,
	Terran_BATTLE_tbawht03_wav = 188,
	Terran_BATTLE_tbayes00_wav = 189,
	Terran_BATTLE_tbayes01_wav = 190,
	Terran_BATTLE_tbayes02_wav = 191,
	Terran_BATTLE_tbayes03_wav = 192,
	Terran_CIVILIAN_TCvPss00_WAV = 193,
	Terran_CIVILIAN_TCvPss01_WAV = 194,
	Terran_CIVILIAN_TCvPss02_WAV = 195,
	Terran_CIVILIAN_TCvPss03_WAV = 196,
	Terran_CIVILIAN_TCvPss04_WAV = 197,
	Terran_CIVILIAN_TCvWht00_WAV = 198,
	Terran_CIVILIAN_TCvWht01_WAV = 199,
	Terran_CIVILIAN_TCvWht02_WAV = 200,
	Terran_CIVILIAN_TCvWht03_WAV = 201,
	Terran_CIVILIAN_TCvYes00_WAV = 202,
	Terran_CIVILIAN_TCvYes01_WAV = 203,
	Terran_CIVILIAN_TCvYes02_WAV = 204,
	Terran_CIVILIAN_TCvYes03_WAV = 205,
	Terran_CIVILIAN_TCvYes04_WAV = 206,
	Terran_CIVILIAN_TCvDth00_WAV = 207,
	Terran_CIVILIAN_TCvRdy00_WAV = 208,
	Terran_DROPSHIP_TDrRdy00_wav = 209,
	Terran_DROPSHIP_TDrDth00_wav = 210,
	Terran_DROPSHIP_TDrPss00_wav = 211,
	Terran_DROPSHIP_TDrPss01_wav = 212,
	Terran_DROPSHIP_TDrPss02_wav = 213,
	Terran_DROPSHIP_TDrPss03_wav = 214,
	Terran_DROPSHIP_TDrWht00_wav = 215,
	Terran_DROPSHIP_TDrWht01_wav = 216,
	Terran_DROPSHIP_TDrWht02_wav = 217,
	Terran_DROPSHIP_TDrWht03_wav = 218,
	Terran_DROPSHIP_TDrYes00_wav = 219,
	Terran_DROPSHIP_TDrYes01_wav = 220,
	Terran_DROPSHIP_TDrYes02_wav = 221,
	Terran_DROPSHIP_TDrYes03_wav = 222,
	Terran_DROPSHIP_TDrYes04_wav = 223,
	Terran_DROPSHIP_TDrYes05_wav = 224,
	Terran_GHOST_TGhRdy00_wav = 225,
	Terran_GHOST_TGhPss00_wav = 226,
	Terran_GHOST_TGhPss01_wav = 227,
	Terran_GHOST_TGhPss02_wav = 228,
	Terran_GHOST_TGhPss03_wav = 229,
	Terran_GHOST_TGhWht00_wav = 230,
	Terran_GHOST_TGhWht01_wav = 231,
	Terran_GHOST_TGhWht02_wav = 232,
	Terran_GHOST_TGhWht03_wav = 233,
	Terran_GHOST_TGhYes00_wav = 234,
	Terran_GHOST_TGhYes01_wav = 235,
	Terran_GHOST_TGhYes02_wav = 236,
	Terran_GHOST_TGhYes03_wav = 237,
	Terran_GHOST_TGhDth00_wav = 238,
	Terran_GHOST_TGhLas00_wav = 239,
	Terran_GHOST_TGhLkd00_wav = 240,
	Terran_GOLIATH_TGoRdy00_wav = 241,
	Terran_GOLIATH_TGoPss00_wav = 242,
	Terran_GOLIATH_TGoPss01_WAV = 243,
	Terran_GOLIATH_TGoPss02_WAV = 244,
	Terran_GOLIATH_TGoPss03_WAV = 245,
	Terran_GOLIATH_TGoPss04_WAV = 246,
	Terran_GOLIATH_TGoPss05_WAV = 247,
	Terran_GOLIATH_TGoWht00_WAV = 248,
	Terran_GOLIATH_TGoWht01_WAV = 249,
	Terran_GOLIATH_TGoWht02_WAV = 250,
	Terran_GOLIATH_TGoWht03_WAV = 251,
	Terran_GOLIATH_TGoYes00_WAV = 252,
	Terran_GOLIATH_TGoYes01_WAV = 253,
	Terran_GOLIATH_TGoYes02_WAV = 254,
	Terran_GOLIATH_TGoYes03_WAV = 255,
	Terran_PHOENIX_TPhRdy00_WAV = 256,
	Terran_PHOENIX_TPhDth00_WAV = 257,
	Terran_PHOENIX_TPhPss00_WAV = 258,
	Terran_PHOENIX_TPhPss01_WAV = 259,
	Terran_PHOENIX_TPhPss02_WAV = 260,
	Terran_PHOENIX_TPhPss03_WAV = 261,
	Terran_PHOENIX_TPhPss04_WAV = 262,
	Terran_PHOENIX_TPhPss05_WAV = 263,
	Terran_PHOENIX_TPhPss06_WAV = 264,
	Terran_PHOENIX_TPhWht00_WAV = 265,
	Terran_PHOENIX_TPhWht01_WAV = 266,
	Terran_PHOENIX_TPhWht02_WAV = 267,
	Terran_PHOENIX_TPhWht03_WAV = 268,
	Terran_PHOENIX_TPhYes00_WAV = 269,
	Terran_PHOENIX_TPhYes01_WAV = 270,
	Terran_PHOENIX_TPhYes02_WAV = 271,
	Terran_PHOENIX_TPhYes03_WAV = 272,
	Terran_PHOENIX_TPhClo00_WAV = 273,
	Terran_PHOENIX_TPhClo01_WAV = 274,
	Terran_MARINE_TMaRdy00_WAV = 275,
	Terran_MARINE_TMaDth00_WAV = 276,
	Terran_MARINE_TMaDth01_WAV = 277,
	Terran_MARINE_TMaSti00_WAV = 278,
	Terran_MARINE_TMaSti01_WAV = 279,
	Terran_MARINE_TMaPss00_WAV = 280,
	Terran_MARINE_TMaPss01_WAV = 281,
	Terran_MARINE_TMaPss02_WAV = 282,
	Terran_MARINE_TMaPss03_WAV = 283,
	Terran_MARINE_TMaPss04_WAV = 284,
	Terran_MARINE_TMaPss05_WAV = 285,
	Terran_MARINE_TMaPss06_WAV = 286,
	Terran_MARINE_TMaWht00_WAV = 287,
	Terran_MARINE_TMaWht01_WAV = 288,
	Terran_MARINE_TMaWht02_WAV = 289,
	Terran_MARINE_TMaWht03_WAV = 290,
	Terran_MARINE_TMaYes00_WAV = 291,
	Terran_MARINE_TMaYes01_WAV = 292,
	Terran_MARINE_TMaYes02_WAV = 293,
	Terran_MARINE_TMaYes03_WAV = 294,
	Terran_Firebat_TFBRdy00_WAV = 295,
	Terran_Firebat_TFBDth00_WAV = 296,
	Terran_Firebat_TFBDth01_WAV = 297,
	Terran_Firebat_TFBDth02_WAV = 298,
	Terran_Firebat_TFBWht00_WAV = 299,
	Terran_Firebat_TFBWht01_WAV = 300,
	Terran_Firebat_TFBWht02_WAV = 301,
	Terran_Firebat_TFBWht03_WAV = 302,
	Terran_Firebat_TFBPss00_WAV = 303,
	Terran_Firebat_TFBPss01_WAV = 304,
	Terran_Firebat_TFBPss02_WAV = 305,
	Terran_Firebat_TFBPss03_WAV = 306,
	Terran_Firebat_TFBPss04_WAV = 307,
	Terran_Firebat_TFBPss05_WAV = 308,
	Terran_Firebat_TFBPss06_WAV = 309,
	Terran_Firebat_TFBYes00_WAV = 310,
	Terran_Firebat_TFBYes01_WAV = 311,
	Terran_Firebat_TFBYes02_WAV = 312,
	Terran_Firebat_TFBYes03_WAV = 313,
	Terran_Firebat_TFBFir00_WAV = 314,
	Terran_Firebat_TFBFir01_WAV = 315,
	Terran_TANK_TTaRdy00_WAV = 316,
	Terran_TANK_TTaDth00_WAV = 317,
	Terran_TANK_TTaTra00_WAV = 318,
	Terran_TANK_TTaTra01_WAV = 319,
	Terran_TANK_TTaPss00_WAV = 320,
	Terran_TANK_TTaPss01_WAV = 321,
	Terran_TANK_TTaPss02_WAV = 322,
	Terran_TANK_TTaPss03_WAV = 323,
	Terran_TANK_TTaWht00_WAV = 324,
	Terran_TANK_TTaWht01_WAV = 325,
	Terran_TANK_TTaWht02_WAV = 326,
	Terran_TANK_TTaWht03_WAV = 327,
	Terran_TANK_TTaYes00_WAV = 328,
	Terran_TANK_TTaYes01_WAV = 329,
	Terran_TANK_TTaYes02_WAV = 330,
	Terran_TANK_TTaYes03_WAV = 331,
	Terran_VESSEL_TVeRdy00_WAV = 332,
	Terran_VESSEL_TVePss00_WAV = 333,
	Terran_VESSEL_TVePss01_WAV = 334,
	Terran_VESSEL_TVePss02_WAV = 335,
	Terran_VESSEL_TVePss03_WAV = 336,
	Terran_VESSEL_TVePss04_WAV = 337,
	Terran_VESSEL_TVePss05_WAV = 338,
	Terran_VESSEL_TVePss06_WAV = 339,
	Terran_VESSEL_TVeWht00_WAV = 340,
	Terran_VESSEL_TVeWht01_WAV = 341,
	Terran_VESSEL_TVeWht02_WAV = 342,
	Terran_VESSEL_TVeWht03_WAV = 343,
	Terran_VESSEL_TVeYes00_WAV = 344,
	Terran_VESSEL_TVeYes01_WAV = 345,
	Terran_VESSEL_TVeYes02_WAV = 346,
	Terran_VESSEL_TVeYes03_WAV = 347,
	Terran_VESSEL_TVeDth00_WAV = 348,
	Terran_VESSEL_TVeDef00_WAV = 349,
	Terran_VESSEL_TVeEmp00_WAV = 350,
	Terran_VESSEL_TVeIrr00_WAV = 351,
	Terran_VULTURE_TVuRdy00_WAV = 352,
	Terran_VULTURE_TVuDth00_WAV = 353,
	Terran_VULTURE_TVuMin01_WAV = 354,
	Terran_VULTURE_TVuMin00_WAV = 355,
	Terran_VULTURE_TVuPss00_WAV = 356,
	Terran_VULTURE_TVuPss01_WAV = 357,
	Terran_VULTURE_TVuPss02_WAV = 358,
	Terran_VULTURE_TVuPss03_WAV = 359,
	Terran_VULTURE_TVuWht00_WAV = 360,
	Terran_VULTURE_TVuWht01_WAV = 361,
	Terran_VULTURE_TVuWht02_WAV = 362,
	Terran_VULTURE_TVuWht03_WAV = 363,
	Terran_VULTURE_TVuYes00_WAV = 364,
	Terran_VULTURE_TVuYes01_WAV = 365,
	Terran_VULTURE_TVuYes02_WAV = 366,
	Terran_VULTURE_TVuYes03_WAV = 367,
	Terran_SCV_TSCRdy00_WAV = 368,
	Terran_SCV_TSCDth00_WAV = 369,
	Terran_SCV_TSCPss00_WAV = 370,
	Terran_SCV_TSCPss01_WAV = 371,
	Terran_SCV_TSCPss02_WAV = 372,
	Terran_SCV_TSCPss03_WAV = 373,
	Terran_SCV_TSCPss04_WAV = 374,
	Terran_SCV_TSCPss05_WAV = 375,
	Terran_SCV_TSCPss06_WAV = 376,
	Terran_SCV_TSCWht00_WAV = 377,
	Terran_SCV_TSCWht01_WAV = 378,
	Terran_SCV_TSCWht02_WAV = 379,
	Terran_SCV_TSCWht03_WAV = 380,
	Terran_SCV_TSCYes00_WAV = 381,
	Terran_SCV_TSCYes01_WAV = 382,
	Terran_SCV_TSCYes02_WAV = 383,
	Terran_SCV_TSCYes03_WAV = 384,
	Terran_bldg_tacwht00_WAV = 385,
	Terran_bldg_tclwht00_WAV = 386,
	Terran_bldg_tcswht00_WAV = 387,
	Terran_bldg_tcsSca00_WAV = 388,
	Terran_bldg_tddwht00_WAV = 389,
	Terran_bldg_tglwht00_WAV = 390,
	Misc_UICWht00_wav = 391,
	Terran_bldg_tmswht00_WAV = 392,
	Terran_bldg_tmtwht00_WAV = 393,
	Misc_UNrWht00_wav = 394,
	Terran_bldg_tRlWht00_WAV = 395,
	Terran_bldg_tnswht00_WAV = 396,
	Terran_bldg_tpgwht00_WAV = 397,
	Terran_bldg_tplwht00_WAV = 398,
	Misc_button_wav = 399,
	Terran_bldg_trewht00_WAV = 400,
	Terran_bldg_trfwht00_WAV = 401,
	Terran_bldg_twpwht00_WAV = 402,
	Terran_bldg_OnFirLrg_wav = 403,
	Terran_SCV_TScTra00_WAV = 404,
	Terran_RAYNORM_URaDth00_WAV = 405,
	Terran_RAYNORM_URaDth01_WAV = 406,
	Terran_RAYNORM_URaPss00_WAV = 407,
	Terran_RAYNORM_URaPss01_WAV = 408,
	Terran_RAYNORM_URaPss02_WAV = 409,
	Terran_RAYNORM_URaPss03_WAV = 410,
	Terran_RAYNORM_URaWht00_WAV = 411,
	Terran_RAYNORM_URaWht01_WAV = 412,
	Terran_RAYNORM_URaWht02_WAV = 413,
	Terran_RAYNORM_URaWht03_WAV = 414,
	Terran_RAYNORM_URaYes00_WAV = 415,
	Terran_RAYNORM_URaYes01_WAV = 416,
	Terran_RAYNORM_URaYes02_WAV = 417,
	Terran_RAYNORM_URaYes03_WAV = 418,
	Terran_RAYNORV_URVPss00_WAV = 419,
	Terran_RAYNORV_URVPss01_WAV = 420,
	Terran_RAYNORV_URVPss02_WAV = 421,
	Terran_RAYNORV_URVPss03_WAV = 422,
	Terran_RAYNORV_URVWht00_WAV = 423,
	Terran_RAYNORV_URVWht01_WAV = 424,
	Terran_RAYNORV_URVWht02_WAV = 425,
	Terran_RAYNORV_URVWht03_WAV = 426,
	Terran_RAYNORV_URVYes00_WAV = 427,
	Terran_RAYNORV_URVYes01_WAV = 428,
	Terran_RAYNORV_URVYes02_WAV = 429,
	Terran_RAYNORV_URVYes03_WAV = 430,
	Terran_DUKET_UDTPss00_WAV = 431,
	Terran_DUKET_UDTPss01_WAV = 432,
	Terran_DUKET_UDTPss02_WAV = 433,
	Terran_DUKET_UDTPss03_WAV = 434,
	Terran_DUKET_UDTPss04_WAV = 435,
	Terran_DUKET_UDTWht00_WAV = 436,
	Terran_DUKET_UDTWht01_WAV = 437,
	Terran_DUKET_UDTWht02_WAV = 438,
	Terran_DUKET_UDTWht03_WAV = 439,
	Terran_DUKET_UDTYes00_WAV = 440,
	Terran_DUKET_UDTYes01_WAV = 441,
	Terran_DUKET_UDTYes02_WAV = 442,
	Terran_DUKET_UDTYes03_WAV = 443,
	Terran_DUKEB_UDupss00_wav = 444,
	Terran_DUKEB_UDupss01_wav = 445,
	Terran_DUKEB_UDupss02_wav = 446,
	Terran_DUKEB_UDupss03_wav = 447,
	Terran_DUKEB_UDupss04_wav = 448,
	Terran_DUKEB_UDuwht00_wav = 449,
	Terran_DUKEB_UDuwht01_wav = 450,
	Terran_DUKEB_UDuwht02_wav = 451,
	Terran_DUKEB_UDuwht03_wav = 452,
	Terran_DUKEB_UDuyes00_wav = 453,
	Terran_DUKEB_UDuyes01_wav = 454,
	Terran_DUKEB_UDuyes02_wav = 455,
	Terran_DUKEB_UDuyes03_wav = 456,
	Terran_KERRIGAN_UKePss00_wav = 457,
	Terran_KERRIGAN_UKePss01_wav = 458,
	Terran_KERRIGAN_UKePss02_wav = 459,
	Terran_KERRIGAN_UKePss03_wav = 460,
	Terran_KERRIGAN_UKePss04_wav = 461,
	Terran_KERRIGAN_UKeWht00_wav = 462,
	Terran_KERRIGAN_UKeWht01_wav = 463,
	Terran_KERRIGAN_UKeWht02_wav = 464,
	Terran_KERRIGAN_UKeWht03_wav = 465,
	Terran_KERRIGAN_UKeYes00_wav = 466,
	Terran_KERRIGAN_UKeYes01_wav = 467,
	Terran_KERRIGAN_UKeYes02_wav = 468,
	Terran_KERRIGAN_UKeYes03_wav = 469,
	Terran_KERRIGAN_UKeDth00_wav = 470,
	Misc_LiftOff_WAV = 471,
	Misc_Land_WAV = 472,
	Protoss_Bldg_pAcWht00_WAV = 473,
	Protoss_Bldg_pAsWht00_WAV = 474,
	Protoss_Bldg_pBaWht00_WAV = 475,
	Protoss_Bldg_pBeWht00_WAV = 476,
	Protoss_Bldg_pCiWht00_WAV = 477,
	Protoss_Bldg_pFoWht00_WAV = 478,
	Protoss_Bldg_pGaWht00_WAV = 479,
	Protoss_Bldg_pGcWht00_WAV = 480,
	Protoss_Bldg_PbaAct00_wav = 481,
	Misc_Button_WAV = 482,
	Protoss_Bldg_pNaWht00_WAV_1 = 483,
	Protoss_Bldg_pNeWht00_WAV = 484,
	Protoss_Bldg_pPBWht00_WAV = 485,
	Misc_UTmWht00_WAV = 486,
	Protoss_Bldg_pPyWht00_WAV = 487,
	Protoss_Bldg_pRoWht00_WAV = 488,
	Misc_UPiWht00_WAV = 489,
	Protoss_Bldg_PTrWht00_WAV = 490,
	Protoss_Bldg_pWaWht00_WAV = 491,
	Protoss_DRAGOON_PDrRdy00_WAV = 492,
	Protoss_DRAGOON_PDrDth00_WAV = 493,
	Protoss_DRAGOON_PDrPss00_WAV = 494,
	Protoss_DRAGOON_PDrPss01_WAV = 495,
	Protoss_DRAGOON_PDrPss02_WAV = 496,
	Protoss_DRAGOON_PDrPss03_WAV = 497,
	Protoss_DRAGOON_PDrWht00_WAV = 498,
	Protoss_DRAGOON_PDrWht01_WAV = 499,
	Protoss_DRAGOON_PDrWht02_WAV = 500,
	Protoss_DRAGOON_PDrWht03_WAV = 501,
	Protoss_DRAGOON_PDrWht04_WAV = 502,
	Protoss_DRAGOON_PDrWht05_WAV = 503,
	Protoss_DRAGOON_PDrWht06_WAV = 504,
	Protoss_DRAGOON_PDrWht07_WAV = 505,
	Protoss_DRAGOON_PDrYes00_WAV = 506,
	Protoss_DRAGOON_PDrYes01_WAV = 507,
	Protoss_DRAGOON_PDrYes02_WAV = 508,
	Protoss_DRAGOON_PDrYes03_WAV = 509,
	Protoss_DRAGOON_PDrYes04_WAV = 510,
	Protoss_DRAGOON_PDrYes05_WAV = 511,
	Protoss_DRAGOON_PDrYes06_WAV = 512,
	Protoss_SHUTTLE_PShRdy00_WAV = 513,
	Protoss_SHUTTLE_PShDth00_WAV = 514,
	Protoss_SHUTTLE_PShPss00_WAV = 515,
	Protoss_SHUTTLE_PShPss01_WAV = 516,
	Protoss_SHUTTLE_PShPss02_WAV = 517,
	Protoss_SHUTTLE_PShPss03_WAV = 518,
	Protoss_SHUTTLE_PShPss04_WAV = 519,
	Protoss_SHUTTLE_PShWht00_WAV = 520,
	Protoss_SHUTTLE_PShWht01_WAV = 521,
	Protoss_SHUTTLE_PShWht02_WAV = 522,
	Protoss_SHUTTLE_PShWht03_WAV = 523,
	Protoss_SHUTTLE_PShYes00_WAV = 524,
	Protoss_SHUTTLE_PShYes01_WAV = 525,
	Protoss_SHUTTLE_PShYes02_WAV = 526,
	Protoss_SHUTTLE_PShYes03_WAV = 527,
	Protoss_SHUTTLE_pshBld00_wav = 528,
	Protoss_SHUTTLE_pshBld03_wav = 529,
	Protoss_SHUTTLE_pshBld01_wav = 530,
	Protoss_SHUTTLE_pshBld02_wav = 531,
	Protoss_SHUTTLE_pshBld04_wav = 532,
	Protoss_Scout_PScDth00_WAV = 533,
	Protoss_SCOUT_PScRdy00_WAV = 534,
	Protoss_Scout_PScPss00_WAV = 535,
	Protoss_Scout_PScPss01_WAV = 536,
	Protoss_Scout_PScPss02_WAV = 537,
	Protoss_Scout_PScPss03_WAV = 538,
	Protoss_Scout_PScPss04_WAV = 539,
	Protoss_Scout_PScWht00_WAV = 540,
	Protoss_Scout_PScWht01_WAV = 541,
	Protoss_Scout_PScWht02_WAV = 542,
	Protoss_Scout_PScWht03_WAV = 543,
	Protoss_Scout_PScYes00_WAV = 544,
	Protoss_Scout_PScYes01_WAV = 545,
	Protoss_Scout_PScYes02_WAV = 546,
	Protoss_Scout_PScYes03_WAV = 547,
	Protoss_ARBITER_PAbCag00_WAV = 548,
	Protoss_ARBITER_PAbRdy00_WAV = 549,
	Protoss_ARBITER_PAbFol00_WAV = 550,
	Protoss_ARBITER_PAbFol01_WAV = 551,
	Protoss_ARBITER_PAbFol02_WAV = 552,
	Protoss_ARBITER_PAbFol03_WAV = 553,
	Protoss_ARBITER_PAbPss00_WAV = 554,
	Protoss_ARBITER_PAbPss01_WAV = 555,
	Protoss_ARBITER_PAbPss02_WAV = 556,
	Protoss_ARBITER_PAbPss03_WAV = 557,
	Protoss_ARBITER_PAbPss04_WAV = 558,
	Protoss_ARBITER_PAbWht00_WAV = 559,
	Protoss_ARBITER_PAbWht01_WAV = 560,
	Protoss_ARBITER_PAbWht02_WAV = 561,
	Protoss_ARBITER_PAbWht03_WAV = 562,
	Protoss_ARBITER_PAbYes00_WAV = 563,
	Protoss_ARBITER_PAbYes01_WAV = 564,
	Protoss_ARBITER_PAbYes02_WAV = 565,
	Protoss_ARBITER_PAbDth00_WAV = 566,
	Protoss_ARCHON_PArRdy00_WAV = 567,
	Protoss_ARCHON_PArMin00_WAV = 568,
	Protoss_ARCHON_PArPss00_WAV = 569,
	Protoss_ARCHON_PArPss01_WAV = 570,
	Protoss_ARCHON_PArPss02_WAV = 571,
	Protoss_ARCHON_PArPss03_WAV = 572,
	Protoss_ARCHON_PArWht00_WAV = 573,
	Protoss_ARCHON_PArWht01_WAV = 574,
	Protoss_ARCHON_PArWht02_WAV = 575,
	Protoss_ARCHON_PArWht03_WAV = 576,
	Protoss_ARCHON_PArYes00_WAV = 577,
	Protoss_ARCHON_PArYes01_WAV = 578,
	Protoss_ARCHON_PArYes02_WAV = 579,
	Protoss_ARCHON_PArYes03_WAV = 580,
	Protoss_ARCHON_PArDth00_WAV = 581,
	Protoss_CARRIER_PCaRdy00_WAV = 582,
	Protoss_Carrier_PCaPss00_WAV = 583,
	Protoss_Carrier_PCaPss01_WAV = 584,
	Protoss_Carrier_PCaPss02_WAV = 585,
	Protoss_Carrier_PCaPss03_WAV = 586,
	Protoss_Carrier_PCaWht00_WAV = 587,
	Protoss_Carrier_PCaWht01_WAV = 588,
	Protoss_Carrier_PCaWht02_WAV = 589,
	Protoss_Carrier_PCaWht03_WAV = 590,
	Protoss_Carrier_PCaYes00_WAV = 591,
	Protoss_Carrier_PCaYes01_WAV = 592,
	Protoss_Carrier_PCaYes02_WAV = 593,
	Protoss_Carrier_PCaYes03_WAV = 594,
	Protoss_Carrier_PCaDth00_WAV = 595,
	Protoss_Carrier_PCaDth01_WAV = 596,
	Protoss_PROBE_PPrRdy00_WAV = 597,
	Protoss_PROBE_PPrDth00_WAV = 598,
	Protoss_PROBE_PPrAtt00_WAV = 599,
	Protoss_PROBE_PPrAtt01_WAV = 600,
	Protoss_PROBE_PPrMin00_WAV = 601,
	Protoss_PROBE_PPrPss00_WAV_1 = 602,
	Protoss_PROBE_PPrPss01_WAV = 603,
	Protoss_PROBE_PPrPss02_WAV = 604,
	Protoss_PROBE_PPrPss03_WAV = 605,
	Protoss_PROBE_PPrWht00_WAV = 606,
	Protoss_PROBE_PPrWht01_WAV = 607,
	Protoss_PROBE_PPrWht02_WAV = 608,
	Protoss_PROBE_PPrWht03_WAV = 609,
	Protoss_PROBE_PPrYes00_WAV = 610,
	Protoss_PROBE_PPrYes01_WAV = 611,
	Protoss_PROBE_PPrYes02_WAV = 612,
	Protoss_PROBE_PPrYes03_WAV = 613,
	Protoss_INTERCEP_PInLau00_WAV = 614,
	Protoss_PROBE_PPrPss00_WAV_2 = 615,
	Protoss_TEMPLAR_PTeSum00_WAV_1 = 616,
	Protoss_TEMPLAR_PTeSum00_WAV_2 = 617,
	Protoss_TEMPLAR_PTeHal00_WAV = 618,
	Protoss_TEMPLAR_PTeHal01_WAV = 619,
	Protoss_TEMPLAR_PTeSto00_WAV = 620,
	Protoss_TEMPLAR_PTeSto01_WAV = 621,
	Protoss_TEMPLAR_PTeRdy00_WAV = 622,
	Protoss_TEMPLAR_PTePss00_WAV = 623,
	Protoss_TEMPLAR_PTePss01_WAV = 624,
	Protoss_TEMPLAR_PTePss02_WAV = 625,
	Protoss_TEMPLAR_PTePss03_WAV = 626,
	Protoss_TEMPLAR_PTeWht00_WAV = 627,
	Protoss_TEMPLAR_PTeWht01_WAV = 628,
	Protoss_TEMPLAR_PTeWht02_WAV = 629,
	Protoss_TEMPLAR_PTeWht03_WAV = 630,
	Protoss_TEMPLAR_PTeYes00_WAV = 631,
	Protoss_TEMPLAR_PTeYes01_WAV = 632,
	Protoss_TEMPLAR_PTeYes02_WAV = 633,
	Protoss_TEMPLAR_PTeYes03_WAV = 634,
	Protoss_TEMPLAR_PTeDth00_WAV = 635,
	Protoss_TEMPLAR_PTeMov00_WAV = 636,
	Protoss_TRILOBYTE_PTrRdy00_WAV = 637,
	Protoss_TRILOBYTE_PTrDth00_WAV = 638,
	Protoss_TRILOBYTE_PTrPss00_WAV = 639,
	Protoss_TRILOBYTE_PTrPss01_WAV = 640,
	Protoss_TRILOBYTE_PTrPss02_WAV = 641,
	Protoss_TRILOBYTE_PTrWht00_WAV = 642,
	Protoss_TRILOBYTE_PTrWht01_WAV = 643,
	Protoss_TRILOBYTE_PTrWht02_WAV = 644,
	Protoss_TRILOBYTE_PTrWht03_WAV = 645,
	Protoss_TRILOBYTE_PTrYes00_WAV = 646,
	Protoss_TRILOBYTE_PTrYes01_WAV = 647,
	Protoss_TRILOBYTE_PTrYes02_WAV = 648,
	Protoss_TRILOBYTE_PTrYes03_WAV = 649,
	Protoss_Witness_PWiRdy00_WAV = 650,
	Protoss_Witness_PWiDth00_WAV = 651,
	Protoss_Witness_PWiDth01_WAV = 652,
	Protoss_Witness_PWiPss00_WAV = 653,
	Protoss_Witness_PWiPss01_WAV = 654,
	Protoss_Witness_PWiPss02_WAV = 655,
	Protoss_Witness_PWiPss03_WAV = 656,
	Protoss_Witness_PWiPss04_WAV = 657,
	Protoss_Witness_PWiWht00_WAV = 658,
	Protoss_Witness_PWiWht01_WAV = 659,
	Protoss_Witness_PWiYes00_WAV = 660,
	Protoss_Witness_PWiYes01_WAV = 661,
	Protoss_ZEALOT_pzeAtt00_WAV = 662,
	Protoss_ZEALOT_pzeAtt01_WAV = 663,
	Protoss_ZEALOT_pzeHit00_WAV = 664,
	Protoss_ZEALOT_PZeRag00_wav = 665,
	Protoss_ZEALOT_PZeRdy00_WAV = 666,
	Protoss_ZEALOT_PZePss00_WAV = 667,
	Protoss_ZEALOT_PZePss01_WAV = 668,
	Protoss_ZEALOT_PZePss02_WAV = 669,
	Protoss_ZEALOT_PZeWht00_WAV = 670,
	Protoss_ZEALOT_PZeWht01_WAV = 671,
	Protoss_ZEALOT_PZeWht02_WAV = 672,
	Protoss_ZEALOT_PZeWht03_WAV = 673,
	Protoss_ZEALOT_PZeYes00_WAV = 674,
	Protoss_ZEALOT_PZeYes01_WAV = 675,
	Protoss_ZEALOT_PZeYes02_WAV = 676,
	Protoss_ZEALOT_PZeYes03_WAV = 677,
	Protoss_ZEALOT_PZeDth00_WAV = 678,
	Protoss_FENIXD_UFdPss00_WAV = 679,
	Protoss_FENIXD_UFdPss01_WAV = 680,
	Protoss_FENIXD_UFdPss02_WAV = 681,
	Protoss_FENIXD_UFdPss03_WAV = 682,
	Protoss_FENIXD_UFdWht00_WAV = 683,
	Protoss_FENIXD_UFdWht01_WAV = 684,
	Protoss_FENIXD_UFdWht02_WAV = 685,
	Protoss_FENIXD_UFdWht03_WAV = 686,
	Protoss_FENIXD_UFdYes00_WAV = 687,
	Protoss_FENIXD_UFdYes01_WAV = 688,
	Protoss_FENIXD_UFdYes02_WAV = 689,
	Protoss_FENIXD_UFdYes03_WAV = 690,
	Protoss_FENIXZ_UFePss00_WAV = 691,
	Protoss_FENIXZ_UFePss01_WAV = 692,
	Protoss_FENIXZ_UFePss02_WAV = 693,
	Protoss_FENIXZ_UFePss03_WAV = 694,
	Protoss_FENIXZ_UFeWht00_WAV = 695,
	Protoss_FENIXZ_UFeWht01_WAV = 696,
	Protoss_FENIXZ_UFeWht02_WAV = 697,
	Protoss_FENIXZ_UFeWht03_WAV = 698,
	Protoss_FENIXZ_UFeYes00_WAV = 699,
	Protoss_FENIXZ_UFeYes01_WAV = 700,
	Protoss_FENIXZ_UFeYes02_WAV = 701,
	Protoss_FENIXZ_UFeYes03_WAV = 702,
	Protoss_GANTRITHOR_UTCPss00_WAV = 703,
	Protoss_GANTRITHOR_UTCPss01_WAV = 704,
	Protoss_GANTRITHOR_UTCPss02_WAV = 705,
	Protoss_GANTRITHOR_UTCPss03_WAV = 706,
	Protoss_GANTRITHOR_UTCWht00_WAV = 707,
	Protoss_GANTRITHOR_UTCWht01_WAV = 708,
	Protoss_GANTRITHOR_UTCWht02_WAV = 709,
	Protoss_GANTRITHOR_UTCWht03_WAV = 710,
	Protoss_GANTRITHOR_UTCYes00_WAV = 711,
	Protoss_GANTRITHOR_UTCYes01_WAV = 712,
	Protoss_GANTRITHOR_UTCYes02_WAV = 713,
	Protoss_GANTRITHOR_UTCYes03_WAV = 714,
	Protoss_TASSADAR_UTaPss00_WAV = 715,
	Protoss_TASSADAR_UTaPss01_WAV = 716,
	Protoss_TASSADAR_UTaPss02_WAV = 717,
	Protoss_TASSADAR_UTaPss03_WAV = 718,
	Protoss_TASSADAR_UTaWht00_WAV = 719,
	Protoss_TASSADAR_UTaWht01_WAV = 720,
	Protoss_TASSADAR_UTaWht02_WAV = 721,
	Protoss_TASSADAR_UTaWht03_WAV = 722,
	Protoss_TASSADAR_UTaYes00_WAV = 723,
	Protoss_TASSADAR_UTaYes01_WAV = 724,
	Protoss_TASSADAR_UTaYes02_WAV = 725,
	Protoss_TASSADAR_UTaYes03_WAV = 726,
	Protoss_TASSADAR_UTaDth00_WAV = 727,
	Protoss_DARKTEMPLAR_PDTRdy00_WAV = 728,
	Protoss_DARKTEMPLAR_PDTPss00_WAV = 729,
	Protoss_DARKTEMPLAR_PDTPss01_WAV = 730,
	Protoss_DARKTEMPLAR_PDTPss02_WAV = 731,
	Protoss_DARKTEMPLAR_PDTPss03_WAV = 732,
	Protoss_DARKTEMPLAR_PDTWht00_WAV = 733,
	Protoss_DARKTEMPLAR_PDTWht01_WAV = 734,
	Protoss_DARKTEMPLAR_PDTWht02_WAV = 735,
	Protoss_DARKTEMPLAR_PDTWht03_WAV = 736,
	Protoss_DARKTEMPLAR_PDTYes00_WAV = 737,
	Protoss_DARKTEMPLAR_PDTYes01_WAV = 738,
	Protoss_DARKTEMPLAR_PDTYes02_WAV = 739,
	Protoss_DARKTEMPLAR_PDTYes03_WAV = 740,
	Protoss_DARKTEMPLAR_PDTDth00_WAV = 741,
	Protoss_ZERATUL_UZePss00_WAV = 742,
	Protoss_ZERATUL_UZePss01_WAV = 743,
	Protoss_ZERATUL_UZePss02_WAV = 744,
	Protoss_ZERATUL_UZePss03_WAV = 745,
	Protoss_ZERATUL_UZeWht00_WAV = 746,
	Protoss_ZERATUL_UZeWht01_WAV = 747,
	Protoss_ZERATUL_UZeWht02_WAV = 748,
	Protoss_ZERATUL_UZeWht03_WAV = 749,
	Protoss_ZERATUL_UZeYes00_WAV = 750,
	Protoss_ZERATUL_UZeYes01_WAV = 751,
	Protoss_ZERATUL_UZeYes02_WAV = 752,
	Protoss_ZERATUL_UZeYes03_WAV = 753,
	Protoss_ZERATUL_UZeDth00_WAV = 754,
	Zerg_Bldg_ZChWht00_WAV = 755,
	Zerg_Bldg_ZCbWht00_WAV = 756,
	Zerg_Bldg_ZEvWht00_WAV = 757,
	Zerg_Bldg_ZFcWht00_WAV = 758,
	Zerg_Bldg_ZHaWht00_WAV = 759,
	Zerg_Bldg_ZHiWht00_WAV = 760,
	Zerg_Bldg_ZIgWht00_WAV = 761,
	Zerg_Bldg_ZLrWht00_WAV = 762,
	Zerg_Bldg_ZLuWht00_WAV = 763,
	Zerg_Bldg_ZMcWht00_WAV = 764,
	Protoss_Bldg_pNaWht00_WAV_2 = 765,
	Zerg_Bldg_ZMhWht00_WAV = 766,
	Zerg_Bldg_ZNeWht00_WAV = 767,
	Zerg_Bldg_ZNyWht00_WAV = 768,
	Zerg_Bldg_ZO1Wht00_WAV = 769,
	Zerg_Bldg_ZRcWht00_WAV = 770,
	Zerg_Bldg_ZSbWht00_WAV = 771,
	Zerg_Bldg_ZScWht00_WAV = 772,
	Zerg_Bldg_ZSpWht00_WAV = 773,
	Zerg_Bldg_ZBldgDth_WAV = 774,
	Zerg_AVENGER_ZAvRdy00_WAV = 775,
	Zerg_AVENGER_ZAvDth00_WAV = 776,
	Zerg_AVENGER_ZAvAtt00_WAV = 777,
	Zerg_AVENGER_ZAvHit00_WAV = 778,
	Zerg_AVENGER_ZAvPss00_WAV = 779,
	Zerg_AVENGER_ZAvPss01_WAV = 780,
	Zerg_AVENGER_ZAvWht00_WAV = 781,
	Zerg_AVENGER_ZAvWht01_WAV = 782,
	Zerg_AVENGER_ZAvYes00_WAV = 783,
	Zerg_AVENGER_ZAvYes01_WAV = 784,
	Zerg_BROODLING_ZBrDth00_WAV = 785,
	Zerg_BROODLING_ZBrAtt00_WAV = 786,
	Zerg_BROODLING_ZBrRdy00_WAV = 787,
	Zerg_BROODLING_ZBrPss00_WAV = 788,
	Zerg_BROODLING_ZBrPss01_WAV = 789,
	Zerg_BROODLING_ZBrPss02_WAV = 790,
	Zerg_BROODLING_ZBrPss03_WAV = 791,
	Zerg_BROODLING_ZBrWht00_WAV = 792,
	Zerg_BROODLING_ZBrWht01_WAV = 793,
	Zerg_BROODLING_ZBrWht02_WAV = 794,
	Zerg_BROODLING_ZBrWht03_WAV = 795,
	Zerg_BROODLING_ZBrYes00_WAV = 796,
	Zerg_BROODLING_ZBrYes01_WAV = 797,
	Zerg_BROODLING_ZBrYes02_WAV = 798,
	Zerg_BUGGUY_ZBGRdy00_wav_1 = 799,
	Zerg_BUGGUY_ZBGRdy00_wav_2 = 800,
	Zerg_BUGGUY_ZBGPss00_wav = 801,
	Zerg_BUGGUY_ZBGPss01_wav = 802,
	Zerg_BUGGUY_ZBGPss02_wav = 803,
	Zerg_BUGGUY_ZBGPss03_wav = 804,
	Zerg_BUGGUY_ZBGWht00_wav = 805,
	Zerg_BUGGUY_ZBGWht01_wav = 806,
	Zerg_BUGGUY_ZBGWht02_wav = 807,
	Zerg_BUGGUY_ZBGWht03_wav = 808,
	Zerg_BUGGUY_ZBGYes00_wav = 809,
	Zerg_BUGGUY_ZBGYes01_wav = 810,
	Zerg_BUGGUY_ZBGYes02_wav = 811,
	Zerg_BUGGUY_ZBGYes03_wav = 812,
	Zerg_DEFILER_ZDeCon00_WAV = 813,
	Zerg_DEFILER_ZDeRdy00_WAV = 814,
	Zerg_DEFILER_ZDeDth00_WAV = 815,
	Zerg_DEFILER_ZDeBlo00_WAV = 816,
	Zerg_DEFILER_ZDeBlo01_WAV = 817,
	Zerg_DEFILER_ZDePss00_WAV = 818,
	Zerg_DEFILER_ZDePss01_WAV = 819,
	Zerg_DEFILER_ZDePss02_WAV = 820,
	Zerg_DEFILER_ZDeWht00_WAV = 821,
	Zerg_DEFILER_ZDeWht01_WAV = 822,
	Zerg_DEFILER_ZDeWht02_WAV = 823,
	Zerg_DEFILER_ZDeYes00_WAV = 824,
	Zerg_DEFILER_ZDeYes01_WAV = 825,
	Zerg_DEFILER_ZDeYes02_WAV = 826,
	Zerg_Egg_ZEgRdy00_WAV = 827,
	Zerg_Egg_ZEgWht00_WAV = 828,
	Zerg_Egg_ZEgWht01_WAV = 829,
	Zerg_Egg_ZEgDth00_WAV = 830,
	Zerg_Egg_ZEgPss00_WAV = 831,
	Zerg_DRONE_ZDrRdy00_WAV = 832,
	Zerg_DRONE_ZDrDth00_WAV = 833,
	Zerg_DRONE_ZDrPss00_WAV = 834,
	Zerg_DRONE_ZDrPss01_WAV = 835,
	Zerg_DRONE_ZDrPss02_WAV = 836,
	Zerg_DRONE_ZDrWht00_WAV = 837,
	Zerg_DRONE_ZDrWht01_WAV = 838,
	Zerg_DRONE_ZDrWht02_WAV = 839,
	Zerg_DRONE_ZDrWht03_WAV = 840,
	Zerg_DRONE_ZDrWht04_WAV = 841,
	Zerg_DRONE_ZDrYes00_WAV = 842,
	Zerg_DRONE_ZDrYes01_WAV = 843,
	Zerg_DRONE_ZDrYes02_WAV = 844,
	Zerg_DRONE_ZDrYes03_WAV = 845,
	Zerg_DRONE_ZDrYes04_WAV = 846,
	Zerg_DRONE_ZDrMin00_wav = 847,
	Zerg_DRONE_ZDrErr00_WAV = 848,
	Zerg_Larva_ZLaDth00_WAV = 849,
	Zerg_Larva_ZLaPss00_WAV = 850,
	Zerg_Larva_ZLaWht00_WAV = 851,
	Zerg_Guardian_ZGuDth00_WAV = 852,
	Zerg_Guardian_ZGuPss00_WAV = 853,
	Zerg_Guardian_ZGuPss01_WAV = 854,
	Zerg_Guardian_ZGuPss02_WAV = 855,
	Zerg_Guardian_ZGuPss03_WAV = 856,
	Zerg_Guardian_ZGuRdy00_WAV = 857,
	Zerg_Guardian_ZGuWht00_WAV = 858,
	Zerg_Guardian_ZGuWht01_WAV = 859,
	Zerg_Guardian_ZGuWht02_WAV = 860,
	Zerg_Guardian_ZGuWht03_WAV = 861,
	Zerg_Guardian_ZGuYes00_WAV = 862,
	Zerg_Guardian_ZGuYes01_WAV = 863,
	Zerg_Guardian_ZGuYes02_WAV = 864,
	Zerg_Guardian_ZGuYes03_WAV = 865,
	Zerg_Hydra_ZHyRdy00_WAV = 866,
	Zerg_Hydra_ZHyDth00_WAV = 867,
	Zerg_Hydra_ZHyPss00_WAV = 868,
	Zerg_Hydra_ZHyPss01_WAV = 869,
	Zerg_Hydra_ZHyWht00_WAV = 870,
	Zerg_Hydra_ZHyWht01_WAV = 871,
	Zerg_Hydra_ZHyWht02_WAV = 872,
	Zerg_Hydra_ZHyYes00_WAV = 873,
	Zerg_Hydra_ZHyYes01_WAV = 874,
	Zerg_Hydra_ZHyYes02_WAV = 875,
	Zerg_Hydra_ZHyYes03_WAV = 876,
	Zerg_Ultra_ZUlRor00_WAV = 877,
	Zerg_Ultra_ZUlDth00_WAV = 878,
	Zerg_Ultra_ZUlPss00_WAV = 879,
	Zerg_Ultra_ZUlPss01_WAV = 880,
	Zerg_Ultra_ZUlPss02_WAV = 881,
	Zerg_Ultra_ZUlRdy00_WAV = 882,
	Zerg_Ultra_ZUlWht00_WAV = 883,
	Zerg_Ultra_ZUlWht01_WAV = 884,
	Zerg_Ultra_ZUlWht02_WAV = 885,
	Zerg_Ultra_ZUlWht03_WAV = 886,
	Zerg_Ultra_ZUlYes00_WAV = 887,
	Zerg_Ultra_ZUlYes01_WAV = 888,
	Zerg_Ultra_ZUlYes02_WAV = 889,
	Zerg_Ultra_ZUlYes03_WAV = 890,
	Zerg_Ultra_zulAtt00_WAV = 891,
	Zerg_Ultra_zulAtt01_WAV = 892,
	Zerg_Ultra_zulAtt02_WAV = 893,
	Zerg_Ultra_zulHit00_WAV = 894,
	Zerg_Ultra_zulHit01_WAV = 895,
	Zerg_Zergling_ZZeDth00_WAV = 896,
	Zerg_Zergling_ZZePss00_WAV = 897,
	Zerg_Zergling_ZZePss01_WAV = 898,
	Zerg_Zergling_ZZePss02_WAV = 899,
	Zerg_Zergling_ZZeRdy00_WAV = 900,
	Zerg_Zergling_ZZeWht00_WAV = 901,
	Zerg_Zergling_ZZeWht01_WAV = 902,
	Zerg_Zergling_ZZeWht02_WAV = 903,
	Zerg_Zergling_ZZeWht03_WAV = 904,
	Zerg_Zergling_ZZeYes00_WAV = 905,
	Zerg_Zergling_ZZeYes01_WAV = 906,
	Zerg_Zergling_ZZeYes02_WAV = 907,
	Zerg_Zergling_ZZeYes03_WAV = 908,
	Zerg_OVERLORD_ZOvRdy00_WAV = 909,
	Zerg_OVERLORD_ZOvDth00_WAV = 910,
	Zerg_OVERLORD_ZOvPss00_WAV = 911,
	Zerg_OVERLORD_ZOvWht00_WAV = 912,
	Zerg_OVERLORD_ZOvWht01_WAV = 913,
	Zerg_OVERLORD_ZOvWht02_WAV = 914,
	Zerg_OVERLORD_ZOvWht03_WAV = 915,
	Zerg_OVERLORD_ZOvYes00_WAV = 916,
	Zerg_OVERLORD_ZOvYes01_WAV = 917,
	Zerg_OVERLORD_ZOvYes02_WAV = 918,
	Zerg_OVERLORD_ZOvYes03_WAV = 919,
	Zerg_Queen_ZQuTag00_WAV = 920,
	Zerg_Queen_ZQuTag01_WAV = 921,
	Zerg_Queen_ZQuSwm00_WAV = 922,
	Zerg_Queen_ZQuSwm01_WAV = 923,
	Zerg_Queen_ZQuEns00_WAV = 924,
	Zerg_Queen_ZQuDth00_WAV = 925,
	Zerg_Queen_ZQuDth01_WAV = 926,
	Zerg_Queen_ZQuDth02_WAV = 927,
	Zerg_Queen_ZQuRdy00_WAV = 928,
	Zerg_Queen_ZQuPss00_WAV = 929,
	Zerg_Queen_ZQuPss01_WAV = 930,
	Zerg_Queen_ZQuPss02_WAV = 931,
	Zerg_Queen_ZQuPss03_WAV = 932,
	Zerg_Queen_ZQuWht00_WAV = 933,
	Zerg_Queen_ZQuWht01_WAV = 934,
	Zerg_Queen_ZQuWht02_WAV = 935,
	Zerg_Queen_ZQuWht03_WAV = 936,
	Zerg_Queen_ZQuYes00_WAV = 937,
	Zerg_Queen_ZQuYes01_WAV = 938,
	Zerg_Queen_ZQuYes02_WAV = 939,
	Zerg_Queen_ZQuYes03_WAV = 940,
	Zerg_Mutalid_ZMuRdy00_WAV = 941,
	Zerg_Mutalid_ZMuDth00_WAV = 942,
	Zerg_Mutalid_ZMuPss00_WAV = 943,
	Zerg_Mutalid_ZMuPss01_WAV = 944,
	Zerg_Mutalid_ZMuPss02_WAV = 945,
	Zerg_Mutalid_ZMuPss03_WAV = 946,
	Zerg_Mutalid_ZMuWht00_WAV = 947,
	Zerg_Mutalid_ZMuWht01_WAV = 948,
	Zerg_Mutalid_ZMuWht02_WAV = 949,
	Zerg_Mutalid_ZMuWht03_WAV = 950,
	Zerg_Mutalid_ZMuYes00_WAV = 951,
	Zerg_Mutalid_ZMuYes01_WAV = 952,
	Zerg_Mutalid_ZMuYes02_WAV = 953,
	Zerg_Mutalid_ZMuYes03_WAV = 954,
	Zerg_ZERGKERRI_UKiPss00_wav = 955,
	Zerg_ZERGKERRI_UKiPss01_wav = 956,
	Zerg_ZERGKERRI_UKiPss02_wav = 957,
	Zerg_ZERGKERRI_UKiPss03_wav = 958,
	Zerg_ZERGKERRI_UKiWht00_wav = 959,
	Zerg_ZERGKERRI_UKiWht01_wav = 960,
	Zerg_ZERGKERRI_UKiWht02_wav = 961,
	Zerg_ZERGKERRI_UKiWht03_wav = 962,
	Zerg_ZERGKERRI_UKiYes00_wav = 963,
	Zerg_ZERGKERRI_UKiYes01_wav = 964,
	Zerg_ZERGKERRI_UKiYes02_wav = 965,
	Zerg_ZERGKERRI_UKiYes03_wav = 966,
	Zerg_ZERGKERRI_UKiDth00_wav = 967,
	Misc_CRITTERS_PbWht01_wav = 968,
	Misc_CRITTERS_PbWht02_wav = 969,
	Misc_CRITTERS_PbWht03_wav = 970,
	Misc_CRITTERS_PBDeath01_wav = 971,
	Misc_CRITTERS_ScWht01_wav = 972,
	Misc_CRITTERS_ScWht02_wav = 973,
	Misc_CRITTERS_ScWht03_wav = 974,
	Misc_CRITTERS_ScDeath01_wav = 975,
	Misc_CRITTERS_TerWht01_wav = 976,
	Misc_CRITTERS_TerWht02_wav = 977,
	Misc_CRITTERS_TerWht03_wav = 978,
	Misc_CRITTERS_TerDeath01_wav = 979,
	Terran_Duran_TDnPss00_wav = 980,
	Terran_Duran_TDnPss01_wav = 981,
	Terran_Duran_TDnPss02_wav = 982,
	Terran_Duran_TDnPss03_wav = 983,
	Terran_Duran_TDnPss04_wav = 984,
	Terran_Duran_TDnPss05_wav = 985,
	Terran_Duran_TDnPss06_wav = 986,
	Terran_Duran_TDnPss07_wav = 987,
	Terran_Duran_TDnPss08_wav = 988,
	Terran_Duran_TDnWht00_wav = 989,
	Terran_Duran_TDnWht01_wav = 990,
	Terran_Duran_TDnWht02_wav = 991,
	Terran_Duran_TDnWht03_wav = 992,
	Terran_Duran_TDnYes00_wav = 993,
	Terran_Duran_TDnYes01_wav = 994,
	Terran_Duran_TDnYes02_wav = 995,
	Terran_Duran_TDnYes03_wav = 996,
	Terran_Duran_TDnDth00_wav = 997,
	Terran_Medic_TmedCure_wav = 998,
	Terran_Medic_TMdRdy00_wav = 999,
	Terran_Medic_TMdDth00_wav = 1000,
	Terran_Medic_TMdWht00_wav = 1001,
	Terran_Medic_TMdWht01_WAV = 1002,
	Terran_Medic_TMdWht02_WAV = 1003,
	Terran_Medic_TMdWht03_wav = 1004,
	Terran_Medic_TMdYes00_wav = 1005,
	Terran_Medic_TMdYes01_wav = 1006,
	Terran_Medic_TMdYes02_wav = 1007,
	Terran_Medic_TMdYes03_wav = 1008,
	Terran_Medic_TMdPss00_wav = 1009,
	Terran_Medic_TMdPss01_WAV = 1010,
	Terran_Medic_TMdPss02_WAV = 1011,
	Terran_Medic_TMdPss03_WAV = 1012,
	Terran_Medic_TMdPss04_WAV = 1013,
	Terran_Medic_TMdPss05_WAV = 1014,
	Terran_Medic_TMdPss06_wav = 1015,
	Terran_Medic_TMedflsh_wav = 1016,
	Terran_Medic_TMedRest_wav = 1017,
	Terran_Medic_TMedHeal_wav = 1018,
	Terran_Medic_Miopia1_wav = 1019,
	Terran_Frigate_AfterOn_wav = 1020,
	Terran_Frigate_AfterOff_wav = 1021,
	Bullet_Tfrhit_wav = 1022,
	Bullet_Tfrshoot_wav = 1023,
	Terran_FRIGATE_TVkRdy00_WAV = 1024,
	Terran_FRIGATE_TVkPss00_WAV = 1025,
	Terran_FRIGATE_TVkPss01_WAV = 1026,
	Terran_FRIGATE_TVkPss02_WAV = 1027,
	Terran_FRIGATE_TVkPss03_WAV = 1028,
	Terran_FRIGATE_TVkPss04_WAV = 1029,
	Terran_FRIGATE_TVkPss05_WAV = 1030,
	Terran_FRIGATE_TVkWht00_WAV = 1031,
	Terran_FRIGATE_TVkWht01_WAV = 1032,
	Terran_FRIGATE_TVkWht02_WAV = 1033,
	Terran_FRIGATE_TVkWht03_WAV = 1034,
	Terran_FRIGATE_TVkYes00_WAV = 1035,
	Terran_FRIGATE_TVkYes01_WAV = 1036,
	Terran_FRIGATE_TVkYes02_WAV = 1037,
	Terran_FRIGATE_TVkYes03_WAV = 1038,
	Terran_FRIGATE_TVkYes04_WAV = 1039,
	Terran_FRIGATE_TVkDth00_WAV = 1040,
	Protoss_Corsair_PCoRdy00_wav = 1041,
	Protoss_Corsair_PCorhit1_wav = 1042,
	Protoss_Corsair_PCorhit2_wav = 1043,
	Protoss_Corsair_PCoWht00_wav = 1044,
	Protoss_Corsair_PCoWht01_WAV = 1045,
	Protoss_Corsair_PCoWht02_WAV = 1046,
	Protoss_Corsair_PCoWht03_wav = 1047,
	Protoss_Corsair_PCoYes00_wav = 1048,
	Protoss_Corsair_PCoYes01_WAV = 1049,
	Protoss_Corsair_PCoYes02_WAV = 1050,
	Protoss_Corsair_PCoYes03_wav = 1051,
	Protoss_Corsair_PCoPss00_wav = 1052,
	Protoss_Corsair_PCoPss01_WAV = 1053,
	Protoss_Corsair_PCoPss02_WAV = 1054,
	Protoss_Corsair_PCoPss03_WAV = 1055,
	Protoss_Corsair_PCoPss04_WAV = 1056,
	Protoss_Corsair_PCoPss05_WAV = 1057,
	Protoss_Corsair_PCoPss06_wav = 1058,
	Protoss_Corsair_PCorWeb1_wav = 1059,
	Protoss_Corsair_PCorlasr2_wav = 1060,
	Protoss_Darchon_feedback_wav = 1061,
	Protoss_Darchon_mind_wav = 1062,
	Protoss_Darchon_ParaAttk_wav = 1063,
	Protoss_Darchon_Parahit_wav = 1064,
	Protoss_DARCHON_PDaRdy00_WAV = 1065,
	Protoss_DARCHON_PDrDth00_WAV = 1066,
	Protoss_DARCHON_PDaPss00_WAV = 1067,
	Protoss_DARCHON_PDaPss01_WAV = 1068,
	Protoss_DARCHON_PDaPss02_WAV = 1069,
	Protoss_DARCHON_PDaPss03_WAV = 1070,
	Protoss_DARCHON_PDaWht00_WAV = 1071,
	Protoss_DARCHON_PDaWht01_WAV = 1072,
	Protoss_DARCHON_PDaWht02_WAV = 1073,
	Protoss_DARCHON_PDaWht03_WAV = 1074,
	Protoss_DARCHON_PDaYes00_WAV = 1075,
	Protoss_DARCHON_PDaYes01_WAV = 1076,
	Protoss_DARCHON_PDaYes02_WAV = 1077,
	Protoss_DARCHON_PDaYes03_WAV = 1078,
	Zerg_LURKER_ZLuRdy00_WAV = 1079,
	Zerg_LURKER_ZLuDth00_WAV = 1080,
	Zerg_LURKER_ZLuPss00_WAV = 1081,
	Zerg_Lurker_ZLuPss01_WAV = 1082,
	Zerg_Lurker_ZLuPss02_WAV = 1083,
	Zerg_LURKER_ZLuPss03_WAV = 1084,
	Zerg_LURKER_ZLuWht00_WAV = 1085,
	Zerg_LURKER_ZLuWht01_WAV = 1086,
	Zerg_LURKER_ZLuWht02_WAV = 1087,
	Zerg_LURKER_ZLuWht03_WAV = 1088,
	Zerg_LURKER_ZLuYes00_WAV = 1089,
	Zerg_LURKER_ZLuYes01_WAV = 1090,
	Zerg_LURKER_ZLuYes02_WAV = 1091,
	Zerg_LURKER_ZLuYes03_WAV = 1092,
	Zerg_LURKER_ZLuBurrw_wav = 1093,
	Zerg_Devourer_firesuck_wav = 1094,
	Zerg_Devourer_goophit_wav = 1095,
	Zerg_Devourer_ZDvRdy00_WAV = 1096,
	Zerg_Devourer_ZDvDth00_WAV = 1097,
	Zerg_Devourer_ZDvPss00_WAV = 1098,
	Zerg_Devourer_ZDvPss01_WAV = 1099,
	Zerg_Devourer_ZDvPss02_WAV = 1100,
	Zerg_Devourer_ZDvWht00_WAV = 1101,
	Zerg_Devourer_ZDvWht01_WAV = 1102,
	Zerg_Devourer_ZDvWht02_WAV = 1103,
	Zerg_Devourer_ZDvYes00_WAV = 1104,
	Zerg_Devourer_ZDvYes01_WAV = 1105,
	Zerg_Devourer_ZDvYes02_WAV = 1106,
	Zerg_Devourer_ZDvYes03_WAV = 1107,
	Bullet_ZLrkFir1_wav = 1108,
	Bullet_ZLrkFir2_wav = 1109,
	Bullet_ZLrkHit1_wav = 1110,
	Bullet_ZLrkHit2_wav = 1111,
	Zerg_ZergDuran_ZDnPss00_wav = 1112,
	Zerg_ZergDuran_ZDnPss01_wav = 1113,
	Zerg_ZergDuran_ZDnPss02_wav = 1114,
	Zerg_ZergDuran_ZDnPss03_wav = 1115,
	Zerg_ZergDuran_ZDnPss04_wav = 1116,
	Zerg_ZergDuran_ZDnPss05_wav = 1117,
	Zerg_ZergDuran_ZDnPss06_wav = 1118,
	Zerg_ZergDuran_ZDnPss07_wav = 1119,
	Zerg_ZergDuran_ZDnPss08_wav = 1120,
	Zerg_ZergDuran_ZDnWht00_wav = 1121,
	Zerg_ZergDuran_ZDnWht01_wav = 1122,
	Zerg_ZergDuran_ZDnWht02_wav = 1123,
	Zerg_ZergDuran_ZDnWht03_wav = 1124,
	Zerg_ZergDuran_ZDnYes00_wav = 1125,
	Zerg_ZergDuran_ZDnYes01_wav = 1126,
	Zerg_ZergDuran_ZDnYes02_wav = 1127,
	Zerg_ZergDuran_ZDnYes03_wav = 1128,
	Zerg_ZergDuran_ZDnDth00_wav = 1129,
	Protoss_Artanis_PAtPss00_wav = 1130,
	Protoss_Artanis_PAtPss01_wav = 1131,
	Protoss_Artanis_PAtPss02_wav = 1132,
	Protoss_Artanis_PAtPss03_wav = 1133,
	Protoss_Artanis_PAtPss04_wav = 1134,
	Protoss_Artanis_PAtPss05_wav = 1135,
	Protoss_Artanis_PAtWht00_wav = 1136,
	Protoss_Artanis_PAtWht01_wav = 1137,
	Protoss_Artanis_PAtWht02_wav = 1138,
	Protoss_Artanis_PAtWht03_wav = 1139,
	Protoss_Artanis_PAtYes00_wav = 1140,
	Protoss_Artanis_PAtYes01_wav = 1141,
	Protoss_Artanis_PAtYes02_wav = 1142,
	Protoss_Artanis_PAtYes03_wav = 1143
};
}

namespace DeathSoundId {

	//Based on IScript.bin playsnd in death sequence
	//First and last id
	//Can be used with this kind of format:
	//	u16 rand_value =	scbw::randBetween(
	//							DeathSoundId::deathSoundIdList[unit->id][0],
	//							DeathSoundId::deathSoundIdList[unit->id][1]
	//						);
	//	scbw::playSound(rand_value);
	const u16 deathSoundIdList[UnitId::None+1][2] = {

		{ SoundId::Terran_MARINE_TMaDth00_WAV, SoundId::Terran_MARINE_TMaDth01_WAV },				//TerranMarine
		{ SoundId::Terran_GHOST_TGhDth00_wav, SoundId::Terran_GHOST_TGhDth00_wav },					//TerranGhost
		{ SoundId::Terran_VULTURE_TVuDth00_WAV, SoundId::Terran_VULTURE_TVuDth00_WAV },				//TerranVulture
		{ SoundId::Misc_ExploMed_wav, SoundId::Misc_ExploMed_wav },									//TerranGoliath
		{ SoundId::No_sound, SoundId::No_sound },													//TerranGoliathTurret
		{ SoundId::Terran_TANK_TTaDth00_WAV, SoundId::Terran_TANK_TTaDth00_WAV },					//TerranSiegeTankTankMode
		{ SoundId::No_sound, SoundId::No_sound },													//TerranSiegeTankTankModeTurret
		{ SoundId::Terran_SCV_TSCDth00_WAV, SoundId::Terran_SCV_TSCDth00_WAV },						//TerranSCV
		{ SoundId::Terran_PHOENIX_TPhDth00_WAV, SoundId::Terran_PHOENIX_TPhDth00_WAV },				//TerranWraith
		{ SoundId::Terran_VESSEL_TVeDth00_WAV, SoundId::Terran_VESSEL_TVeDth00_WAV },				//TerranScienceVessel
		{ SoundId::Terran_Firebat_TFBDth00_WAV, SoundId::Terran_Firebat_TFBDth02_WAV },				//Hero_GuiMontag
		{ SoundId::Terran_DROPSHIP_TDrDth00_wav, SoundId::Terran_DROPSHIP_TDrDth00_wav },			//TerranDropship
		{ SoundId::Terran_BATTLE_tbaDth00_wav, SoundId::Terran_BATTLE_tbaDth00_wav },				//TerranBattlecruiser
		{ SoundId::No_sound,  SoundId::No_sound },													//TerranVultureSpiderMine
		{ SoundId::No_sound,  SoundId::No_sound },													//TerranNuclearMissile
		{ SoundId::Terran_MARINE_TMaDth00_WAV, SoundId::Terran_MARINE_TMaDth01_WAV },				//TerranCivilian
		{ SoundId::Terran_KERRIGAN_UKeDth00_wav, SoundId::Terran_KERRIGAN_UKeDth00_wav },			//Hero_SarahKerrigan
		{ SoundId::Misc_ExploMed_wav, SoundId::Misc_ExploMed_wav },									//Hero_AlanSchezar
		{ SoundId::No_sound,  SoundId::No_sound },													//Hero_AlanSchezarTurret
		{ SoundId::Terran_VULTURE_TVuDth00_WAV, SoundId::Terran_VULTURE_TVuDth00_WAV },				//Hero_JimRaynorVulture
		{ SoundId::Terran_MARINE_TMaDth00_WAV, SoundId::Terran_MARINE_TMaDth01_WAV },				//Hero_JimRaynorMarine
		{ SoundId::Terran_PHOENIX_TPhDth00_WAV, SoundId::Terran_PHOENIX_TPhDth00_WAV },				//Hero_TomKazansky
		{ SoundId::Terran_VESSEL_TVeDth00_WAV, SoundId::Terran_VESSEL_TVeDth00_WAV },				//Hero_Magellan
		{ SoundId::Terran_TANK_TTaDth00_WAV, SoundId::Terran_TANK_TTaDth00_WAV },					//Hero_EdmundDukeTankMode
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Hero_EdmundDukeTankModeTurret
		{ SoundId::Terran_TANK_TTaDth00_WAV, SoundId::Terran_TANK_TTaDth00_WAV },					//Hero_EdmundDukeSiegeMode
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Hero_EdmundDukeSiegeModeTurret
		{ SoundId::Terran_BATTLE_tbaDth00_wav, SoundId::Terran_BATTLE_tbaDth00_wav },				//Hero_ArcturusMengsk
		{ SoundId::Terran_BATTLE_tbaDth00_wav, SoundId::Terran_BATTLE_tbaDth00_wav },				//Hero_Hyperion
		{ SoundId::Terran_BATTLE_tbaDth00_wav, SoundId::Terran_BATTLE_tbaDth00_wav },				//Hero_NoradII
		{ SoundId::Terran_TANK_TTaDth00_WAV, SoundId::Terran_TANK_TTaDth00_WAV }, 					//TerranSiegeTankSiegeMode
		{ SoundId::No_sound,  SoundId::No_sound }, 													//TerranSiegeTankSiegeModeTurret
		{ SoundId::Terran_Firebat_TFBDth00_WAV, SoundId::Terran_Firebat_TFBDth02_WAV },				//TerranFirebat
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Spell_ScannerSweep
		{ SoundId::Terran_Medic_TMdDth00_wav, SoundId::Terran_Medic_TMdDth00_wav },					//TerranMedic
		{ SoundId::Zerg_Larva_ZLaDth00_WAV, SoundId::Zerg_Larva_ZLaDth00_WAV }, 					//ZergLarva
		{ SoundId::Zerg_Egg_ZEgDth00_WAV, SoundId::Zerg_Egg_ZEgDth00_WAV }, 						//ZergEgg
		{ SoundId::Zerg_Zergling_ZZeDth00_WAV, SoundId::Zerg_Zergling_ZZeDth00_WAV },				//ZergZergling
		{ SoundId::Zerg_Hydra_ZHyDth00_WAV, SoundId::Zerg_Hydra_ZHyDth00_WAV }, 					//ZergHydralisk
		{ SoundId::Zerg_Ultra_ZUlDth00_WAV, SoundId::Zerg_Ultra_ZUlDth00_WAV }, 					//ZergUltralisk
		{ SoundId::Zerg_BROODLING_ZBrDth00_WAV, SoundId::Zerg_BROODLING_ZBrDth00_WAV },				//ZergBroodling
		{ SoundId::Zerg_DRONE_ZDrDth00_WAV, SoundId::Zerg_DRONE_ZDrDth00_WAV },						//ZergDrone
		{ SoundId::Zerg_OVERLORD_ZOvDth00_WAV, SoundId::Zerg_OVERLORD_ZOvDth00_WAV },				//ZergOverlord
		{ SoundId::Zerg_Mutalid_ZMuDth00_WAV, SoundId::Zerg_Mutalid_ZMuDth00_WAV }, 				//ZergMutalisk
		{ SoundId::Zerg_Guardian_ZGuDth00_WAV, SoundId::Zerg_Guardian_ZGuDth00_WAV },				//ZergGuardian
		{ SoundId::Zerg_Queen_ZQuDth00_WAV, SoundId::Zerg_Queen_ZQuDth02_WAV }, 					//ZergQueen
		{ SoundId::Zerg_DEFILER_ZDeDth00_WAV, SoundId::Zerg_DEFILER_ZDeDth00_WAV },					//ZergDefiler
		{ SoundId::Zerg_AVENGER_ZAvDth00_WAV, SoundId::Zerg_AVENGER_ZAvDth00_WAV },					//ZergScourge
		{ SoundId::Zerg_Ultra_ZUlDth00_WAV, SoundId::Zerg_Ultra_ZUlDth00_WAV },						//Hero_Torrasque
		{ SoundId::Zerg_Queen_ZQuDth00_WAV, SoundId::Zerg_Queen_ZQuDth02_WAV },						//Hero_Matriarch
		{ SoundId::Bullet_ZBGHit00_wav, SoundId::Bullet_ZBGHit00_wav },								//ZergInfestedTerran
		{ SoundId::Zerg_ZERGKERRI_UKiDth00_wav, SoundId::Zerg_ZERGKERRI_UKiDth00_wav },				//Hero_InfestedKerrigan
		{ SoundId::Zerg_DEFILER_ZDeDth00_WAV, SoundId::Zerg_DEFILER_ZDeDth00_WAV },					//Hero_UncleanOne
		{ SoundId::Zerg_Hydra_ZHyDth00_WAV, SoundId::Zerg_Hydra_ZHyDth00_WAV }, 					//Hero_HunterKiller
		{ SoundId::Zerg_Zergling_ZZeDth00_WAV, SoundId::Zerg_Zergling_ZZeDth00_WAV },				//Hero_DevouringOne
		{ SoundId::Zerg_Mutalid_ZMuDth00_WAV, SoundId::Zerg_Mutalid_ZMuDth00_WAV }, 				//Hero_KukulzaMutalisk
		{ SoundId::Zerg_Guardian_ZGuDth00_WAV, SoundId::Zerg_Guardian_ZGuDth00_WAV },				//Hero_KukulzaGuardian
		{ SoundId::Zerg_OVERLORD_ZOvDth00_WAV, SoundId::Zerg_OVERLORD_ZOvDth00_WAV },				//Hero_Yggdrasill
		{ SoundId::Terran_FRIGATE_TVkDth00_WAV, SoundId::Terran_FRIGATE_TVkDth00_WAV },				//TerranValkyrie
		{ SoundId::Zerg_Mutalid_ZMuDth00_WAV, SoundId::Zerg_Mutalid_ZMuDth00_WAV }, 				//ZergCocoon
		{ SoundId::Protoss_Scout_PScDth00_WAV, SoundId::Protoss_Scout_PScDth00_WAV },				//ProtossCorsair
		{ SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV, SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV },	//ProtossDarkTemplar
		{ SoundId::Zerg_Devourer_ZDvDth00_WAV, SoundId::Zerg_Devourer_ZDvDth00_WAV }, 				//ZergDevourer
		{ SoundId::Misc_ExploLrg_wav, SoundId::Misc_ExploLrg_wav },									//ProtossDarkArchon
		{ SoundId::Protoss_PROBE_PPrDth00_WAV, SoundId::Protoss_PROBE_PPrDth00_WAV },				//ProtossProbe
		{ SoundId::Protoss_ZEALOT_PZeDth00_WAV, SoundId::Protoss_ZEALOT_PZeDth00_WAV },				//ProtossZealot
		{ SoundId::Protoss_DRAGOON_PDrDth00_WAV, SoundId::Protoss_DRAGOON_PDrDth00_WAV },			//ProtossDragoon
		{ SoundId::Protoss_TEMPLAR_PTeDth00_WAV, SoundId::Protoss_TEMPLAR_PTeDth00_WAV },			//ProtossHighTemplar
		{ SoundId::Misc_ExploLrg_wav, SoundId::Misc_ExploLrg_wav },									//ProtossArchon
		{ SoundId::Protoss_SHUTTLE_PShDth00_WAV,  SoundId::Protoss_SHUTTLE_PShDth00_WAV }, 			//ProtossShuttle
		{ SoundId::Protoss_Scout_PScDth00_WAV,  SoundId::Protoss_Scout_PScDth00_WAV },				//ProtossScout
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossArbiter
		{ SoundId::Protoss_Carrier_PCaDth00_WAV,  SoundId::Protoss_Carrier_PCaDth01_WAV }, 			//ProtossCarrier
		{ SoundId::Misc_ExploMed_wav,  SoundId::Misc_ExploMed_wav }, 								//ProtossInterceptor
		{ SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV,  SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV }, 	//Hero_DarkTemplar
		{ SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV,  SoundId::Protoss_DARKTEMPLAR_PDTDth00_WAV }, 	//Hero_Zeratul
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Hero_TassadarZeratulArchon
		{ SoundId::Protoss_ZEALOT_PZeDth00_WAV,  SoundId::Protoss_ZEALOT_PZeDth00_WAV }, 			//Hero_FenixZealot
		{ SoundId::Protoss_DRAGOON_PDrDth00_WAV,  SoundId::Protoss_DRAGOON_PDrDth00_WAV },			//Hero_FenixDragoon
		{ SoundId::Protoss_TEMPLAR_PTeDth00_WAV,  SoundId::Protoss_TEMPLAR_PTeDth00_WAV }, 			//Hero_Tassadar
		{ SoundId::Protoss_Scout_PScDth00_WAV,  SoundId::Protoss_Scout_PScDth00_WAV }, 				//Hero_Mojo
		{ SoundId::Protoss_TRILOBYTE_PTrDth00_WAV,  SoundId::Protoss_TRILOBYTE_PTrDth00_WAV },		//Hero_Warbringer
		{ SoundId::Protoss_Carrier_PCaDth00_WAV,  SoundId::Protoss_Carrier_PCaDth01_WAV }, 			//Hero_Gantrithor
		{ SoundId::Protoss_TRILOBYTE_PTrDth00_WAV,  SoundId::Protoss_TRILOBYTE_PTrDth00_WAV }, 		//ProtossReaver
		{ SoundId::Protoss_Witness_PWiDth00_WAV,  SoundId::Protoss_Witness_PWiDth01_WAV }, 			//ProtossObserver
		{ SoundId::No_sound,  SoundId::No_sound }, 													//ProtossScarab
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Hero_Danimoth
		{ SoundId::Protoss_TEMPLAR_PTeDth00_WAV,  SoundId::Protoss_TEMPLAR_PTeDth00_WAV },			//Hero_Aldaris
		{ SoundId::Protoss_Scout_PScDth00_WAV,  SoundId::Protoss_Scout_PScDth00_WAV }, 				//Hero_Artanis
		{ SoundId::Misc_CRITTERS_BCrDth00_wav,  SoundId::Misc_CRITTERS_BCrDth00_wav }, 				//Critter_Rhynadon
		{ SoundId::Misc_CRITTERS_JCrDth00_wav,  SoundId::Misc_CRITTERS_JCrDth00_wav }, 				//Critter_Bengalaas
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_CargoShip
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_MercenaryGunship
		{ SoundId::Misc_CRITTERS_ScDeath01_wav,  SoundId::Misc_CRITTERS_ScDeath01_wav },			//Critter_Scantid
		{ SoundId::Misc_CRITTERS_TerDeath01_wav,  SoundId::Misc_CRITTERS_TerDeath01_wav },			//Critter_Kakaru
		{ SoundId::Misc_CRITTERS_LCrDth00_wav,  SoundId::Misc_CRITTERS_LCrDth00_wav }, 				//Critter_Ragnasaur
		{ SoundId::Misc_CRITTERS_PBDeath01_wav,  SoundId::Misc_CRITTERS_PBDeath01_wav }, 			//Critter_Ursadon
		{ SoundId::Zerg_Egg_ZEgDth00_WAV,  SoundId::Zerg_Egg_ZEgDth00_WAV }, 						//ZergLurkerEgg
		{ SoundId::Protoss_Scout_PScDth00_WAV,  SoundId::Protoss_Scout_PScDth00_WAV }, 				//Hero_Raszagal
		{ SoundId::Terran_GHOST_TGhDth00_wav,  SoundId::Terran_GHOST_TGhDth00_wav }, 				//Hero_SamirDuran
		{ SoundId::Terran_GHOST_TGhDth00_wav,  SoundId::Terran_GHOST_TGhDth00_wav }, 				//Hero_AlexeiStukov
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_MapRevealer
		{ SoundId::Terran_BATTLE_tbaDth00_wav,  SoundId::Terran_BATTLE_tbaDth00_wav }, 				//Hero_GerardDuGalle
		{ SoundId::Zerg_LURKER_ZLuDth00_WAV,  SoundId::Zerg_LURKER_ZLuDth00_WAV }, 					//ZergLurker
		{ SoundId::Terran_GHOST_TGhDth00_wav,  SoundId::Terran_GHOST_TGhDth00_wav }, 				//Hero_InfestedDuran
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Spell_DisruptionWeb
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//TerranCommandCenter
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//TerranComsatStation
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//TerranNuclearSilo
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranSupplyDepot
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranRefinery
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranBarracks
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranAcademy
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranFactory
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranStarport
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranControlTower
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranScienceFacility
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranCovertOps
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranPhysicsLab
		{ SoundId::No_sound,  SoundId::No_sound },													//UnusedTerran1
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranMachineShop
		{ SoundId::No_sound,  SoundId::No_sound },													//UnusedTerran2
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranEngineeringBay
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranArmory
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranMissileTurret
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//TerranBunker
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//Special_CrashedNoradII
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav },								//Special_IonCannon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_UrajCrystal
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_KhalisCrystal
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ZergInfestedCommandCenter
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV },						//ZergHatchery
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergLair
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergHive
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergNydusCanal
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergHydraliskDen
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergDefilerMound
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergGreaterSpire
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergQueensNest
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergEvolutionChamber
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergUltraliskCavern
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergSpire
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergSpawningPool
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergCreepColony
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergSporeColony
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedZerg1
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergSunkenColony
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//Special_OvermindWithShell
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//Special_Overmind
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//ZergExtractor
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//Special_MatureChrysalis
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//Special_Cerebrate
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV }, 						//Special_CerebrateDaggoth
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedZerg2
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossNexus
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossRoboticsFacility
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossPylon
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossAssimilator
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedProtoss1
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossObservatory
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossGateway
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedProtoss2
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossPhotonCannon
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossCitadelofAdun
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossCyberneticsCore
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossTemplarArchives
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossForge
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossStargate
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_StasisCellPrison
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossFleetBeacon
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossArbiterTribunal
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossRoboticsSupportBay
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//ProtossShieldBattery
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_KhaydarinCrystalForm
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_ProtossTemple
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_XelNagaTemple
		{ SoundId::No_sound,  SoundId::No_sound }, 													//ResourceMineralField
		{ SoundId::No_sound,  SoundId::No_sound }, 													//ResourceMineralFieldType2
		{ SoundId::No_sound,  SoundId::No_sound }, 													//ResourceMineralFieldType3
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedCave
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedCaveIn
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedCantina
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedMiningPlatform
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedIndependentCommandCenter
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_IndependentStarport
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedIndependentJumpGate
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedRuins
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedKhaydarinCrystalFormation
		{ SoundId::No_sound,  SoundId::No_sound }, 													//ResourceVespeneGeyser
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_WarpGate
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_PsiDisrupter
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedZergMarker
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedTerranMarker
		{ SoundId::No_sound,  SoundId::No_sound }, 													//UnusedProtossMarker
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_ZergBeacon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_TerranBeacon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_ProtossBeacon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_ZergFlagBeacon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_TerranFlagBeacon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_ProtossFlagBeacon
		{ SoundId::Misc_ExploLrg_wav,  SoundId::Misc_ExploLrg_wav }, 								//Special_PowerGenerator
		{ SoundId::Zerg_Bldg_ZBldgDth_WAV,  SoundId::Zerg_Bldg_ZBldgDth_WAV },						//Special_OvermindCocoon
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Spell_DarkSwarm
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_FloorMissileTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_FloorHatch
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_UpperLevelDoor
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_RightUpperLevelDoor
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_PitDoor
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_RightPitDoor
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_FloorGunTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_WallMissileTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_WallFlameTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_RightWallMissileTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_RightWallFlameTrap
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Special_StartLocation
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_Flag
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_YoungChrysalis
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_PsiEmitter
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_DataDisk
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_KhaydarinCrystal
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_MineralClusterType1
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_MineralClusterType2
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_ProtossGasOrbType1
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_ProtossGasOrbType2
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_ZergGasSacType1
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_ZergGasSacType2
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_TerranGasTankType1
		{ SoundId::No_sound,  SoundId::No_sound }, 													//Powerup_TerranGasTankType2
		{ SoundId::No_sound,  SoundId::No_sound }  													//None

	};
}
